### ISSUE TITLE
SpreadSheet Plural example

### ISSUE THREAD

**Issue by baptiste-faure1811** [AckeeCZ/ACKLocalization#28]
Hello ;) 
Is it possible to add a spreadsheet example that has plurals ? I can't figure out how to make it work ? 
English os not my native language and I am not sure to understand correctly how to use: translation.key##{zero}
Thanks in advance

**Comment by olejnjak** [comment]
Sure, thanks for the input 🙂 Basically it just copies behavior from [native stringsdicts](https://developer.apple.com/documentation/xcode/localizing-strings-that-contain-plurals) so in the sheet you have key in whatever form you want and just append the plural category/rule so you end up with keys like `key##{zero}`, `key##{one}`, `key##{few}`, `key##{many}`, `key##{other}`

**Comment by LukasHromadnik** [comment]
Here you can see an example from one of our projects

<img width="581" alt="Snímek obrazovky 2022-04-12 v 10 42 40" src="https://user-images.githubusercontent.com/2185200/162919499-602f2c0b-7f65-41e4-8c25-1e1c9a6e7566.png">

**Comment by baptiste-faure1811** [comment]
Thank you !! You answered so fast I almost missed the email. Perfect, thanks a lot 🎉
